version: '3'
services:
  ourapython:
    build: .
    container_name: ourapython
    command: python /etc/oura/oura_post_to_influxdb.py
    secrets:
      - OuraApiToken
      - InfluxDBToken
    environment:
      - BUCKET=${BUCKET:-OuraDB}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=${INFLUXDB_ORG:-my-org}
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    networks:
      - ouradb

  influxdb:
    container_name: ourainfluxdb
    image: influxdb:2.7.3-alpine
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - ouradb
    volumes:
      - OuraDB-influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-my-org}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET:-OuraDB}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  grafana:
    container_name: ouragrafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ouradb
    links:
      - influxdb
    volumes:
      - OuraDB-grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  OuraDB-influxdb: {}
  OuraDB-grafana: {}
  OuraDB-chronograf: {}
networks:
  ouradb:
    driver: bridge

secrets:
  OuraApiToken:
    file: "${OURA_PAT}"
  InfluxDBToken:
    environment: "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"