version: '3'
services:
  ourapython:
    build: .
    container_name: ourapython
    command: python /etc/oura/oura_post_to_influxdb.py
    secrets:
      - OuraApiToken
      - InfluxDBToken
    environment:
      - BUCKET=${BUCKET:-OuraDB}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=${INFLUXDB_ORG:-my-org}
secrets:
  OuraApiToken:
    external: true
    name: "${OURA_PAT}"
  InfluxDBToken:
    external: true
    name: "${INFLUXDB_TOKEN}"